# dependabot.yml file with updates

version: 2
updates:
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
    labels:
      - "app"
      - "security"
      - "dependencies"
    open-pull-requests-limit: 1
    target-branch: "develop"

  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: weekly
    labels:
      - "api"
      - "security"
      - "dependencies"
    open-pull-requests-limit: 1
    target-branch: "develop"

  - package-ecosystem: npm
    directory: /backoffice
    schedule:
      interval: weekly
    labels:
      - "backoffice"
      - "security"
      - "dependencies"
    open-pull-requests-limit: 1
    target-branch: "develop"
