# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Hermes re-enabled (Oct 2025) - MapLibre 10.2.1 should be compatible now
# Previously disabled in Jan 2024 (commit 08b3266) due to iOS bug with older MapLibre version
# ENV['USE_HERMES'] = '0'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Désactiver l'utilisation de l'IDFA pour Firebase Analytics
$RNFirebaseAnalyticsWithoutAdIdSupport = true

target 'aireal' do
  config = use_native_modules!
	
	use_frameworks! :linkage => :static
	$RNFirebaseAsStaticFramework = true
  $RNFirebaseAnalyticsWithoutAdIdSupport=true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'airealTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # MapLibre post_install must be called after react_native_post_install
    $MLRN.post_install(installer)
  end
end
